import { Tray } from '../trays/trayType';
export const coldTrays: Tray = [
  {
    type: 'Cold',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/nuggetTray_md_PDP_Desk.png',
    name: 'Salad Tray',
    variants: null,
    utensil: 'Tong',
    notes:
      'If guest does no specify dressing, we will provide Avocado Lime Ranch',
    sizes: {
      small: {
        serving_size: 5,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: [
          'Avocado Lime Ranch - 2',
          'Garden Herb Ranch - 2',
          'Zesty Apple Cider Vinaigrette - 1',
          'Fat-Free Honey Mustard - 1',
          'Light Italian - 1',
          'Light Balsamic Vinaigrette - 1',
          'Creamy Salsa - 1',
        ],
      },
      medium: null,
      large: {
        serving_size: 10,
        quantity: 0,
        honey: 0,
        free8oz: 0,
        roasted_almonds: 0,
        dressings: [
          'Avocado Lime Ranch - 3',
          'Garden Herb Ranch - 3',
          'Zesty Apple Cider Vinaigrette - 2',
          'Fat-Free Honey Mustard - 2',
          'Light Italian - 2',
          'Light Balsamic Vinaigrette - 2',
          'Creamy Salsa - 1',
        ],
      },
    },
  },
  /// spacing
  {
    type: 'Cold',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/nuggetTray_md_PDP_Desk.png',
    name: 'Fruit Tray',
    variants: null,
    utensil: 'Spoon',
    notes: null,
    sizes: {
      small: {
        serving_size: 12,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      medium: null,
      large: {
        serving_size: 26,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  /// spacing
  {
    type: 'Cold',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/nuggetTray_md_PDP_Desk.png',
    name: 'Kale Tray',
    variants: null,
    utensil: 'Tong',
    notes: null,
    sizes: {
      small: {
        serving_size: 10,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      medium: {
        serving_size: 0,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      large: {
        serving_size: 20,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  /// spacing
  {
    type: 'Cold',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/nuggetTray_md_PDP_Desk.png',
    name: 'Grilled Wrap Tray',
    variants: ['Spicy Grilled Wrap Tray', 'Veggie Wrap Tray'],
    utensil: 'Tong',
    notes:
      'If guest does no specify dressing, we will provide Avocado Lime Ranch',
    sizes: {
      small: {
        serving_size: 6,
        quantity: 6,
        honey: 0,
        free8oz: 0,
        roasted_almonds: 0,
        dressings: [
          'Avocado Lime Ranch - 1',
          'Garden Herb Ranch - 1',
          'Zesty Apple Cider Vinaigrette - 1',
          'Fat-Free Honey Mustard - 1',
          'Light Italian - 1',
          'Light Balsamic Vinaigrette - 1',
          'Creamy Salsa - 1',
        ],
      },
      medium: {
        serving_size: 10,
        quantity: 10,
        honey: 0,
        free8oz: 0,
        roasted_almonds: 0,
        dressings: [
          'Avocado Lime Ranch - 1',
          'Garden Herb Ranch - 1',
          'Zesty Apple Cider Vinaigrette - 1',
          'Fat-Free Honey Mustard - 1',
          'Light Italian - 1',
          'Light Balsamic Vinaigrette - 1',
          'Creamy Salsa - 1',
        ],
      },
      large: {
        serving_size: 14,
        quantity: 14,
        honey: 0,
        free8oz: 0,
        roasted_almonds: 20,
        dressings: [
          'Avocado Lime Ranch - 1',
          'Garden Herb Ranch - 1',
          'Zesty Apple Cider Vinaigrette - 1',
          'Fat-Free Honey Mustard - 1',
          'Light Italian - 1',
          'Light Balsamic Vinaigrette - 1',
          'Creamy Salsa - 1',
        ],
      },
    },
  },
];
