import { Tray } from '../trays/trayType';
export const hotTrays: Tray = [
  {
    type: 'Hot',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/nuggetTray_md_PDP_Desk.png',
    name: 'Nugget Tray',
    variants: ['Chilled'],
    utensil: 'Tong',
    notes: null,
    sizes: {
      small: {
        serving_size: 8,
        quantity: 64,
        honey: null,
        free8oz: 1,
        roasted_almonds: null,
        dressings: null,
      },
      medium: {
        serving_size: 15,
        quantity: 120,
        honey: null,
        free8oz: 1,
        roasted_almonds: null,
        dressings: null,
      },
      large: {
        serving_size: 25,
        quantity: 200,
        honey: null,
        free8oz: 2,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  {
    type: 'Hot',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/StripsTray_Medium_CFASauce_BBQSauce_desk.png',
    name: 'Strip Tray',
    variants: [],
    utensil: 'Tong',
    notes: null,
    sizes: {
      small: {
        serving_size: 8,
        quantity: 24,
        honey: null,
        free8oz: 1,
        roasted_almonds: null,
        dressings: null,
      },
      medium: {
        serving_size: 15,
        quantity: 45,
        honey: null,
        free8oz: 1,
        roasted_almonds: null,
        dressings: null,
      },
      large: {
        serving_size: 25,
        quantity: 75,
        honey: null,
        free8oz: 2,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  {
    type: 'Hot',
    img: 'https://www.cfacdn.com/img/order/COM/Menu_Refresh/Catering/Catering%20Desktop/031417_MacnCheese_SmTray_CateringSize_Prod_CMYK_0038-V4_2880px.png',
    name: 'Mac N Cheese Tray',
    variants: null,
    utensil: 'Spoon',
    notes: null,
    sizes: {
      small: null,
      medium: {
        serving_size: 10,
        quantity: null,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      large: {
        serving_size: 20,
        quantity: 0,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  {
    type: 'Hot',
    img: 'https://www.cfacdn.com/img/order/menu/Online/Trays/minisTray_lg_PDP_Desk.png',
    name: 'Chick-n-Minis Tray',
    variants: null,
    utensil: 'Tong',
    notes: null,
    sizes: {
      small: {
        serving_size: 5,
        quantity: 20,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      medium: null,
      large: {
        serving_size: 10,
        quantity: 40,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
    },
  },
  {
    type: 'Hot',
    img: 'https://www.cfacdn.com/img/order/COM/Menu_Refresh/Catering/Catering%20Desktop/031417_MacnCheese_SmTray_CateringSize_Prod_CMYK_0038-V4_2880px.png',
    name: 'Grilled Fillet Bundle',
    variants: null,
    utensil: 'Tong 3x',
    notes:
      'Includes 10 grilled filets, 10 multigrain buns, 1 Honey Roasted BBQ Sauce',
    sizes: {
      small: null,
      medium: {
        serving_size: 10,
        quantity: 10,
        honey: null,
        free8oz: null,
        roasted_almonds: null,
        dressings: null,
      },
      large: null,
    },
  },
];
